stages:
  - minify

minify_js:
  image: node:latest
  stage: minify
  before_script:
    - npm install uglify-js -g
  script:
    - mkdir -p ./dist/js
    - uglifyjs js/API.js --output dist/js/API.min.js 
  artifacts:
    expire_in: 1 week
    paths:
      - dist

minify_css:
  image: node:latest
  stage: minify
  before_script:
    - npm install uglifycss -g
  script:
    - mkdir -p ./dist/css
    - uglifycss css/style.css css/animations.css css/form.css --output dist/css/style.min.css
  artifacts:
    expire_in: 1 week
    paths:
      - dist